Repository Shteb/Kais-NPC-Rebake-LCP, pull requests merged in 2025-03, with the labels that each got.

#65 fix(grunts): move stat tweaks to feat bonuses, revise some feats
  NPC Rebakes/npc_classes.json
  NPC Rebakes/npc_features.json
Labels: breaking change

#72 [DATA] Address issue #69: Pyro and Archer
  NPC Rebakes/npc_classes.json
  NPC Rebakes/npc_features.json
Labels: bug

#73 [Feature] Add manifest, class, and features for the deployables lcp
  Rebake Deployables/lcp_manifest.json
  Rebake Deployables/npc_classes.json
  Rebake Deployables/npc_features.json
Labels: enhancement
