Repository Shteb/Kais-NPC-Rebake-LCP, pull requests merged in 2025-01, with the labels that each got.

#4 Github action that bundles the LCP when releases are created
  .github/workflows/actions.yml
  NPC Rebakes.lcp
Labels: enhancement

#6 Fixed LCP Bundler
  .github/workflows/actions.yml
Labels: bug

#7 Hive Class
  NPC Rebakes/npc_classes.json
  NPC Rebakes/npc_features.json
Labels: enhancement, help wanted, good first issue

#8 Minor Fixes
  NPC Rebakes/npc_features.json
Labels: help wanted, good first issue

#5 Support Class
  NPC Rebakes/npc_classes.json
  NPC Rebakes/npc_features.json
Labels: enhancement, help wanted, good first issue

#12 [Fix] Use temp file correctly when bumping manifest version
  .github/workflows/actions.yml
Labels: bug

#14 Minor fixes #3
  NPC Rebakes/lcp_manifest.json
  NPC Rebakes/npc_classes.json
  NPC Rebakes/npc_features.json
Labels: help wanted, good first issue

#11 Adding Strong text to NPC Features for Breacher - Specter
  NPC Rebakes/npc_features.json
Labels: help wanted, good first issue

#18 Properly pipe contents of `lcp_manifest.tmp.json` into `jq`
  .github/workflows/actions.yml
Labels: bug

#19 Adding-Sniper
  NPC Rebakes/lcp_manifest.json
  NPC Rebakes/npc_classes.json
  NPC Rebakes/npc_features.json
Labels: enhancement, help wanted, good first issue
